<a href="https://colab.research.google.com/github/izzat-ai/learning-ai/blob/main/projects/formula_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

- **Juzeppe Farinaning 1950-yilgi chempionligidan bugungi kungacha bo'lgan har bir poyga, haydovchi, konstruktor, saralash sessiyasi va F1 tarixidagi o'rni**

- `cons_standing` - Ochkolar va pozitsiyalar
- `cons` - Jamoalar nomlari
- `races` - Yillar va poyga nomlari
- `results` - Har bir poyga natijalari

In [5]:
import numpy as np
import pandas as pd

In [6]:
cons_standing = pd.read_csv("/content/drive/MyDrive/AI learning/ai_project_2026/formula1/f1_constructor_standings.csv")
cons = pd.read_csv("/content/drive/MyDrive/AI learning/ai_project_2026/formula1/f1_constructors.csv")
races = pd.read_csv("/content/drive/MyDrive/AI learning/ai_project_2026/formula1/f1_races.csv")
results = pd.read_csv("/content/drive/MyDrive/AI learning/ai_project_2026/formula1/f1_results.csv")

#####**Data cleaning**

1. cons_standing cleaning
2. cons cleaning
3. races cleaning
4. results cleaning

In [7]:
cons_standing.head()

   season  position  points  wins constructor_id constructor
0    1958       1.0    48.0     6        vanwall     Vanwall
1    1958       2.0    40.0     2        ferrari     Ferrari
2    1958       3.0    31.0     2         cooper      Cooper
3    1958       4.0    18.0     0            brm         BRM
4    1958       5.0     6.0     0       maserati    Maserati

In [8]:
cons_standing.shape

(924, 6)

In [9]:
# determine how many blank values ​​are in each column
cons_standing.isnull().sum()

season              0
position          212
points              0
wins                0
constructor_id      0
constructor         0
dtype: int64

In [15]:
# check for negative values
cons_standing[cons_standing['position'] < 0]

Empty DataFrame
Columns: [season, position, points, wins, constructor_id, constructor]
Index: []

In [16]:
cons.head()

,constructor_id,name,nationality,url
0,adams,Adams,American,https://en.wikipedia.org/wiki/Adams_(constructor)
1,afm,AFM,German,https://en.wikipedia.org/wiki/Alex_von_Falkenh...
2,ags,AGS,French,https://en.wikipedia.org/wiki/Automobiles_Gonf...
3,alfa,Alfa Romeo,Swiss,https://en.wikipedia.org/wiki/Alfa_Romeo_in_Fo...
4,alphatauri,AlphaTauri,Italian,https://en.wikipedia.org/wiki/Scuderia_AlphaTauri