<a href="https://colab.research.google.com/github/izzat-ai/learning-ai/blob/main/projects/Bank_customer_churn_project/bank_cutomer_ch_prediction.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
import pandas as pd

In [2]:
df_tr = pd.read_csv("/content/drive/MyDrive/AI learning/ai_project_2026/bank_prediction/train.csv")
df_tr.head()

,id,CustomerId,Surname,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
0,0,15702656.0,Nwora,567.0,France,Male,33.0,9.0,0.0,2.0,1.0,0.0,156792.89,0.0
1,1,15647965.0,Yevdokimova,628.0,France,Female,38.0,3.0,0.0,1.0,1.0,1.0,51987.99,1.0
2,2,15798834.0,Ch'iu,635.0,France,Female,29.0,3.0,0.0,2.0,1.0,1.0,113079.19,0.0
3,3,15672056.0,Hsia,681.0,France,Male,28.0,6.0,0.0,2.0,1.0,0.0,14081.64,0.0
4,4,15759537.0,Okwudilichukwu,587.0,France,Female,27.0,5.0,0.0,2.0,1.0,0.0,158958.90,0.0

In [3]:
df_te = pd.read_csv("/content/drive/MyDrive/AI learning/ai_project_2026/bank_prediction/test.csv")
df_te.head()

,id,CustomerId,Surname,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary
0,15000,15732563.0,Hs?,707.0,Germany,Male,21.0,4.0,114513.66,2.0,1.0,0.0,176692.87
1,15001,15727041.0,Ma,678.0,Germany,Male,33.0,5.0,142510.50,1.0,0.0,0.0,52820.13
2,15002,15753679.0,K?,636.0,Spain,Male,45.0,9.0,0.00,2.0,1.0,1.0,125062.02
3,15003,15581554.0,H?,697.0,Spain,Male,46.0,8.0,0.00,2.0,1.0,0.0,131647.41
4,15004,15773723.0,Bellucci,553.0,Spain,Male,31.0,2.0,0.00,2.0,1.0,0.0,58814.41

In [4]:
df_tr.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 15000 entries, 0 to 14999
Data columns (total 14 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   id               15000 non-null  int64
 1   CustomerId       15000 non-null  float64
 2   Surname          15000 non-null  object
 3   CreditScore      15000 non-null  float64
 4   Geography        15000 non-null  object
 5   Gender           15000 non-null  object
 6   Age              15000 non-null  float64
 7   Tenure           15000 non-null  float64
 8   Balance          15000 non-null  float64
 9   NumOfProducts    15000 non-null  float64
 10  HasCrCard        15000 non-null  float64
 11  IsActiveMember   15000 non-null  float64
 12  EstimatedSalary  15000 non-null  float64
 13  Exited           15000 non-null  float64
dtypes: float64(10), int64(1), object(3)
memory usage: 1.6+ MB

1. Age ustuni float turida , uni butun sonli ma'lumotga o'zgartirish kerak
2. Tenure ham huddi Age kabi holatda
3. NumOfProducts ustuni ham int turida bo'lishi kerak
4. HasCard ham intda bo'lishi kerak
5. IsActive ustuni ham intda bo'lishi kerak
6. Exited ustuni ham intda bo'lishi kerak

- trian datafremesidagi holatlarda bu dfdayam takrorlanadi faqat test datada Exited ustuni yo'q

In [6]:
# target ustunini taqsimotini ko'rish
df_tr['Exited'].value_counts()

Exited
0.0    12023
1.0     2977
Name: count, dtype: int64

In [7]:
# taqsimotni foiz qilib ko'rish
df_tr['Exited'].value_counts(normalize=True)*100

Exited
0.0    80.153333
1.0    19.846667
Name: proportion, dtype: float64

- Demak , Bankda qolgan mijozlar 80% , bankdan ketgan mijozlar esa deyarli 20% ni tashkil qilmoqda . Ya'ni train DataFramemiz ma'lumotlari balansda emas .

In [18]:
# guruhlangan ustunlarni mijozni ketishiga qay darajada bog'liqligini aniqlash
cols = df_tr[['Geography', 'Gender', 'NumOfProducts', 'IsActiveMember']]

for col in cols:
  res = df_tr.groupby(col)['Exited'].mean()*100
  print("\n", res, "\n")

 Geography
France     15.387168
Germany    40.597015
Spain      15.182927
Name: Exited, dtype: float64


 Gender
Female    27.552898
Male      13.918377
Name: Exited, dtype: float64


 NumOfProducts
1.0     38.015363
2.0      4.151796
3.0     95.360825
4.0     85.000000
5.0    100.000000
Name: Exited, dtype: float64


 IsActiveMember
0.0    27.314815
1.0    12.258065
Name: Exited, dtype: float64

In [21]:
# barcha sonli ustunlarni Target ustuni bilan bog'liqligini ko'rish
corr = df_tr.corr(numeric_only=True)['Exited'].sort_values(ascending=False)
corr

Exited             1.000000
Age                0.449425
Balance            0.160062
EstimatedSalary    0.035193
CustomerId        -0.004122
HasCrCard         -0.010670
id                -0.015533
Tenure            -0.032897
CreditScore       -0.052375
IsActiveMember    -0.188748
NumOfProducts     -0.312812
Name: Exited, dtype: float64

In [24]:
import matplotlib.pyplot as plt
import seaborn as sns