<a href="https://colab.research.google.com/github/izzat-ai/learning-ai/blob/main/pandas/football_Liga_datasets_practice.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
import pandas as pd

In [2]:
! wget https://raw.githubusercontent.com/datasets/football-datasets/refs/heads/main/datasets/premier-league/season-0001.csv
! wget https://raw.githubusercontent.com/datasets/football-datasets/refs/heads/main/datasets/la-liga/season-0001.csv
! wget https://raw.githubusercontent.com/datasets/football-datasets/refs/heads/main/datasets/bundesliga/season-0001.csv

--2026-10-17 05:29:53--  https://raw.githubusercontent.com/datasets/football-datasets/refs/heads/main/datasets/premier-league/season-0001.csv
Resolving raw.githubusercontent.com (raw.githubusercontent.com)... 185.199.108.133, 185.199.109.133, 185.199.110.133, ...
Connecting to raw.githubusercontent.com (raw.githubusercontent.com)|185.199.108.133|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 31022 (30K) [text/plain]
Saving to: ‘season-0001.csv’

season-0001.csv     100%[===================>]  30.29K  --.-KB/s    in 0.002s

2026-10-17 05:29:53 (19.0 MB/s) - ‘season-0001.csv’ saved [31022/31022]

--2026-10-17 05:29:53--  https://raw.githubusercontent.com/datasets/football-datasets/refs/heads/main/datasets/la-liga/season-0001.csv
Resolving raw.githubusercontent.com (raw.githubusercontent.com)... 185.199.111.133, 185.199.108.133, 185.199.110.133, ...
Connecting to raw.githubusercontent.com (raw.githubusercontent.com)|185.199.111.133|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 20769 (20K) [text/plain]
Saving to: ‘season-0001.csv.1’

season-0001.csv.1   100%[===================>]  20.28K  --.-KB/s    in 0.001s

2026-10-17 05:29:54 (13.6 MB/s) - ‘season-0001.csv.1’ saved [20769/20769]

--2026-10-17 05:29:54--  https://raw.githubusercontent.com/datasets/football-datasets/refs/heads/main/datasets/bundesliga/season-0001.csv
Resolving raw.githubusercontent.com (raw.githubusercontent.com)... 185.199.108.133, 185.199.109.133, 185.199.110.133, ...
Connecting to raw.githubusercontent.com (raw.githubusercontent.com)|185.199.108.133|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 27037 (26K) [text/plain]
Saving to: ‘season-0001.csv.2’

season-0001.csv.2   100%[===================>]  26.40K  --.-KB/s    in 0.002s

2026-10-17 05:29:54 (15.3 MB/s) - ‘season-0001.csv.2’ saved [27037/27037]

In [8]:
# Premier Liga
df1 = pd.read_csv("/content/season-0001.csv")
df1.head()

,Date,HomeTeam,AwayTeam,FTHG,FTAG,FTR,HTHG,HTAG,HTR,Referee,...,HST,AST,HF,AF,HC,AC,HY,AY,HR,AR
0,2000-08-19,Charlton,Man City,4,0,H,2,0,H,Rob Harris,...,14,4,13,12,6,6,1,2,0,0
1,2000-08-19,Chelsea,West Ham,4,2,H,1,0,H,Graham Barber,...,10,5,19,14,7,7,1,2,0,0
2,2000-08-19,Coventry,Middlesbrough,1,3,A,1,1,D,Barry Knight,...,3,9,15,21,8,4,5,3,1,0
3,2000-08-19,Derby,Southampton,2,2,D,1,2,A,Andy D'Urso,...,4,6,11,13,5,8,1,1,0,0
4,2000-08-19,Leeds,Everton,2,0,H,2,0,H,Dermot Gallagher,...,8,6,21,20,6,4,1,3,0,0

In [6]:
# LaLiga dataset
df2 = pd.read_csv("/content/season-0001.csv.1")
df2.head()

,Date,HomeTeam,AwayTeam,FTHG,FTAG,FTR,HTHG,HTAG,HTR,Referee,...,HST,AST,HF,AF,HC,AC,HY,AY,HR,AR
0,2000-09-09,Barcelona,Malaga,2,1,H,2,0,H,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,2000-09-09,La Coruna,Ath Bilbao,2,0,H,0,0,D,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,2000-09-09,Real Madrid,Valencia,2,1,H,0,0,D,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,2000-09-09,Sociedad,Santander,2,2,D,0,0,D,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,2000-09-09,Zaragoza,Espanol,1,2,A,0,0,D,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [7]:
# BundesLiga dataset
df3 = pd.read_csv("/content/season-0001.csv.2")
df3.head()

,Date,HomeTeam,AwayTeam,FTHG,FTAG,FTR,HTHG,HTAG,HTR,Referee,...,HST,AST,HF,AF,HC,AC,HY,AY,HR,AR
0,2000-08-11,Dortmund,Hansa Rostock,1,0,H,0,0,D,Jörg Kessler,...,7,2,25,19,7,3,1,5,0,0
1,2000-08-12,Bayern Munich,Hertha,4,1,H,1,0,H,Markus Merk,...,6,5,13,12,4,9,1,0,0,0
2,2000-08-12,Freiburg,Stuttgart,4,0,H,2,0,H,Helmut Krug,...,7,5,22,17,4,7,1,1,0,0
3,2000-08-12,Hamburg,Munich 1860,2,2,D,2,2,D,Herbert Fandel,...,5,7,0,0,5,3,2,2,0,1
4,2000-08-12,Kaiserslautern,Bochum,0,1,A,0,0,D,Helmut Fleischer,...,2,2,9,8,5,5,1,0,0,0

**DF ustunlari**

- FTHG (Full Time Home Team Goals): Meybon jamoasining to'liq o'yin (90 daqiqa) davomida urgan gollari soni.   
- FTAG (Full Time Away Team Goals): Mehmon jamoasining to'liq o'yin davomida urgan gollari soni.   
- FTR (Full Time Result): O'yinning yakuniy natijasi:H = Home Win (Meybon jamoa g'alabasi)   A = Away Win (Mehmon jamoa g'alabasi)   D = Draw (Durang)   
- HTHG (Half Time Home Team Goals): Birinchi bo'limda (taymda) mezbon jamoa urgan gollar soni.   
- HTAG (Half Time Away Team Goals): Birinchi bo'limda mehmon jamoa urgan gollar soni.   
- HTR (Half Time Result): Birinchi bo'lim yakuniy natijasi (H, A yoki D)


- HS (Home Shots): Mezbon jamoaning darvoza tomonga yo'llagan barcha zarbalari soni.
- AS (Away Shots): Mehmon jamoaning darvoza tomonga yo'llagan barcha zarbalari soni.
- HST (Home Shots on Target): Mezbon jamoaning aniq (darvoza sohasiga borgan) zarbalari soni.   
- AST (Away Shots on Target): Mehmon jamoaning aniq zarbalari soni.   
- HF (Home Fouls): Mezbon jamoa tomonidan ishlatilgan fol (qoida buzilish)lar soni.   
- AF (Away Fouls): Mehmon jamoa tomonidan ishlatilgan follar soni.   
- HC (Home Corners): Mezbon jamoaning burchak zarbalari (korner) soni.   
- AC (Away Corners): Mehmon jamoaning burchak zarbalari soni

In [11]:
# LaLiga ohirgi 5 ta qator ma'lumotlarini ko'rish
df2.tail()

,Date,HomeTeam,AwayTeam,FTHG,FTAG,FTR,HTHG,HTAG,HTR,Referee,...,HST,AST,HF,AF,HC,AC,HY,AY,HR,AR
375,2001-06-17,La Coruna,Malaga,4,0,H,1,0,H,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
376,2001-06-17,Mallorca,Oviedo,4,2,H,1,0,H,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
377,2001-06-17,Real Madrid,Valladolid,2,1,H,1,0,H,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
378,2001-06-17,Sociedad,Osasuna,0,1,A,0,1,A,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
379,2001-06-17,Zaragoza,Celta,1,1,D,0,0,D,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [12]:
df2.sample(5)

,Date,HomeTeam,AwayTeam,FTHG,FTAG,FTR,HTHG,HTAG,HTR,Referee,...,HST,AST,HF,AF,HC,AC,HY,AY,HR,AR
286,2001-04-08,Osasuna,Santander,1,1,D,1,1,D,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
41,2000-10-14,Real Madrid,La Coruna,3,0,H,2,0,H,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
374,2001-06-17,Barcelona,Valencia,3,2,H,2,1,H,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
267,2001-03-18,Vallecano,Oviedo,0,2,A,0,1,A,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
164,2001-01-07,Oviedo,Barcelona,2,3,A,0,2,A,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [13]:
# LaLiga datasetini hajmi
df2.shape

(380, 22)

In [14]:
# Primier ligani hajmi
df1.shape

(380, 22)

In [15]:
# bundesligani hajmi
df3.shape

(306, 22)

- BundesLiga datasetining ma'lumotlari qolgan ikki datasetnikidan kamroq ekan

In [16]:
# primier liga dataseti umumiy ma'lumotlari
df1.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 380 entries, 0 to 379
Data columns (total 22 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   Date      380 non-null    object
 1   HomeTeam  380 non-null    object
 2   AwayTeam  380 non-null    object
 3   FTHG      380 non-null    int64
 4   FTAG      380 non-null    int64
 5   FTR       380 non-null    object
 6   HTHG      380 non-null    int64
 7   HTAG      380 non-null    int64
 8   HTR       380 non-null    object
 9   Referee   380 non-null    object
 10  HS        380 non-null    int64
 11  AS        380 non-null    int64
 12  HST       380 non-null    int64
 13  AST       380 non-null    int64
 14  HF        380 non-null    int64
 15  AF        380 non-null    int64
 16  HC        380 non-null    int64
 17  AC        380 non-null    int64
 18  HY        380 non-null    int64
 19  AY        380 non-null    int64
 20  HR        380 non-null    int64
 21  AR        380 non-null    int64
dtypes: int64(16), object(6)
memory usage: 65.4+ KB

1. Date ustuni objectda turibdi , uni date formatida qilish kerak

In [17]:
# LaLiga dataseti umumiy ma'lumotlari
df2.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 380 entries, 0 to 379
Data columns (total 22 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   Date      380 non-null    object
 1   HomeTeam  380 non-null    object
 2   AwayTeam  380 non-null    object
 3   FTHG      380 non-null    int64
 4   FTAG      380 non-null    int64
 5   FTR       380 non-null    object
 6   HTHG      380 non-null    int64
 7   HTAG      380 non-null    int64
 8   HTR       380 non-null    object
 9   Referee   0 non-null      float64
 10  HS        0 non-null      float64
 11  AS        0 non-null      float64
 12  HST       0 non-null      float64
 13  AST       0 non-null      float64
 14  HF        0 non-null      float64
 15  AF        0 non-null      float64
 16  HC        0 non-null      float64
 17  AC        0 non-null      float64
 18  HY        0 non-null      float64
 19  AY        0 non-null      float64
 20  HR        0 non-null      float64
 21  AR        0 non-null      float64
dtypes: float64(13), int64(4), object(5)
memory usage: 65.4+ KB

1. Date ustuni objectda turibdi , date formatiga o'tkizish kerak
2. Referee ustunidan boshlab qolgan barcha ustunlar NaN lar bilan to'lgan

In [19]:
# BundesLiga dataseti umumiy ma'lumotlari
df3.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 306 entries, 0 to 305
Data columns (total 22 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   Date      306 non-null    object
 1   HomeTeam  306 non-null    object
 2   AwayTeam  306 non-null    object
 3   FTHG      306 non-null    int64
 4   FTAG      306 non-null    int64
 5   FTR       306 non-null    object
 6   HTHG      306 non-null    int64
 7   HTAG      306 non-null    int64
 8   HTR       306 non-null    object
 9   Referee   305 non-null    object
 10  HS        306 non-null    int64
 11  AS        306 non-null    int64
 12  HST       306 non-null    int64
 13  AST       306 non-null    int64
 14  HF        306 non-null    int64
 15  AF        306 non-null    int64
 16  HC        306 non-null    int64
 17  AC        306 non-null    int64
 18  HY        306 non-null    int64
 19  AY        306 non-null    int64
 20  HR        306 non-null    int64
 21  AR        306 non-null    int64
dtypes: int64(16), object(6)
memory usage: 52.7+ KB

1. Bunda ham Date usutni objectda

In [20]:
# PremierLiga ma'lumotlari
df1.describe()

,FTHG,FTAG,HTHG,HTAG,HS,AS,HST,AST,HF,AF,HC,AC,HY,AY,HR,AR
count,380.000000,380.000000,380.000000,380.000000,380.000000,380.000000,380.000000,380.000000,380.000000,380.000000,380.000000,380.000000,380.000000,380.000000,380.000000,380.000000
mean,1.544737,1.065789,0.686842,0.476316,12.792105,9.378947,6.163158,4.531579,12.978947,13.944737,6.289474,4.647368,1.347368,1.794737,0.084211,0.081579
std,1.285436,1.029070,0.843623,0.694469,4.859117,3.609366,2.991582,2.239382,4.164757,4.382695,3.001388,2.742583,1.260468,1.309585,0.287402,0.292704
min,0.000000,0.000000,0.000000,0.000000,0.000000,2.000000,0.000000,0.000000,0.000000,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,1.000000,0.000000,0.000000,0.000000,9.000000,7.000000,4.000000,3.000000,10.000000,11.000000,4.000000,3.000000,0.000000,1.000000,0.000000,0.000000
50%,1.000000,1.000000,0.000000,0.000000,12.000000,9.000000,6.000000,4.000000,13.000000,13.000000,6.000000,4.000000,1.000000,2.000000,0.000000,0.000000
75%,2.000000,2.000000,1.000000,1.000000,16.000000,12.000000,8.000000,6.000000,16.000000,17.000000,8.000000,6.000000,2.000000,3.000000,0.000000,0.000000
max,6.000000,4.000000,5.000000,4.000000,33.000000,24.000000,19.000000,14.000000,25.000000,28.000000,17.000000,14.000000,7.000000,7.000000,2.000000,2.000000

In [21]:
df1.describe(include='all')

,Date,HomeTeam,AwayTeam,FTHG,FTAG,FTR,HTHG,HTAG,HTR,Referee,...,HST,AST,HF,AF,HC,AC,HY,AY,HR,AR
count,380,380,380,380.000000,380.000000,380,380.000000,380.000000,380,380,...,380.000000,380.000000,380.000000,380.000000,380.000000,380.000000,380.000000,380.000000,380.000000,380.000000
unique,97,20,20,NaN,NaN,3,NaN,NaN,3,29,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
top,2001-05-19,Charlton,Man City,NaN,NaN,H,NaN,NaN,D,Alan Wiley,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
freq,10,19,19,NaN,NaN,184,NaN,NaN,152,23,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
mean,NaN,NaN,NaN,1.544737,1.065789,NaN,0.686842,0.476316,NaN,NaN,...,6.163158,4.531579,12.978947,13.944737,6.289474,4.647368,1.347368,1.794737,0.084211,0.081579
std,NaN,NaN,NaN,1.285436,1.029070,NaN,0.843623,0.694469,NaN,NaN,...,2.991582,2.239382,4.164757,4.382695,3.001388,2.742583,1.260468,1.309585,0.287402,0.292704
min,NaN,NaN,NaN,0.000000,0.000000,NaN,0.000000,0.000000,NaN,NaN,...,0.000000,0.000000,0.000000,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,NaN,NaN,NaN,1.000000,0.000000,NaN,0.000000,0.000000,NaN,NaN,...,4.000000,3.000000,10.000000,11.000000,4.000000,3.000000,0.000000,1.000000,0.000000,0.000000
50%,NaN,NaN,NaN,1.000000,1.000000,NaN,0.000000,0.000000,NaN,NaN,...,6.000000,4.000000,13.000000,13.000000,6.000000,4.000000,1.000000,2.000000,0.000000,0.000000
75%,NaN,NaN,NaN,2.000000,2.000000,NaN,1.000000,1.000000,NaN,NaN,...,8.000000,6.000000,16.000000,17.000000,8.000000,6.000000,2.000000,3.000000,0.000000,0.000000
max,NaN,NaN,NaN,6.000000,4.000000,NaN,5.000000,4.000000,NaN,NaN,...,19.000000,14.000000,25.000000,28.000000,17.000000,14.000000,7.000000,7.000000,2.000000,2.000000